### PR TITLE
Item interest

### PR DESCRIPTION
**Pull request by joshuaSmith2021**
This adds wishlist support to the backend. This is a step in supporting a seller marking an item as "sold", as ideally they will be able to look at whose interested. Once they have given the item away, they can mark the item as "sold/given" to a user.

For testing, I added an item to `josh.smith`'s wishlist, attempting re-adding it and verifying correct behavior, removing the item, and removing it again and verifying correct behavior.

### CODE REVIEW

**Comment by sribala20** [comment]
LGTM

**Review by sribala20 — APPROVED** [review]
LGTM, we can continue updating the endpoints.md too, nice addition

**Comment by joshuaSmith2021** [comment]
> LGTM, we can continue updating the endpoints.md too, nice addition

Sounds good, my next task is adding authentication and I'll update the README with authentication info

**Comment by davepatel2** [comment]
looks great to me, ik its closed but I still reviewed

**Comment by KeithJLZ** [comment]
Didn't realize we had to physically leave comments. Nothing else I think should be changed.

**Pull request merged**
